# /* ----------- 💫 https://github.com/JaKooLit 💫 -------- */ #

[pyprland]

plugins = ["scratchpads", "magnify"]

# [scratchpads.term]
# animation = "fromTop"
# command = "kitty --class kitty-dropterm"
# class = "kitty-dropterm"
# size = "75% 60%"


[scratchpads.term]
animation = "fromTop"
command = "ghostty"
class = "kitty-dropterm"
size = "75% 60%"
