# /* ----------- 💫 https://github.com/JaKooLit 💫 -------- */ #

[pyprland]

plugins = ["scratchpads", "magnify"]

[scratchpads.term]
animation = "fromTop"
command = "ghostty --class=\"com.ghostty.ghostty-dropterm\""
class = "com.ghostty.ghostty-dropterm"
size = "75% 60%"
